#!/bin/zsh
#runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_hybrid tune_smac_cost_aware_hand
#runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_algo tune_smac_cost_aware_hand


runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_gpu_h100 ppo_gpu_hybrid tune_smac_cost_aware_hand
