#!/bin/zsh

#runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_hybrid tune_smac_cost_aware_hand
#runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_hybrid tune_smac_cost_aware_rf
runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_hybrid tune_smac
#runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_hybrid tune_smac_mf
runscripts/rs_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_hybrid tune_rs


runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_algo tune_smac
#runscripts/smac_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_algo tune_smac_mf
runscripts/rs_claix.sh box2d_lunar_lander_ppo claix_cpu ppo_cpu_algo tune_rs

