seed: 0
name: ppo_cpu_hybrid
hyperparameters:
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    log: true
  hp_config.gamma:
    type: uniform_float
    upper: 0.999
    lower: 0.95
    log: false
  hp_config.gae_lambda:
    type: uniform_float
    upper: 0.9999
    lower: 0.8
    log: false
  hp_config.ent_coef:
    type: uniform_float
    upper: 0.5 
    lower: 0.0
    log: false
  hp_config.vf_coef:
    type: uniform_float
    upper: 1.0
    lower: 0.0
    default_value: 0.5
    log: false
  hp_config.minibatch_size:
    type: ordinal
    sequence: [64, 128, 256, 512, 1024]
  hp_config.n_steps:
    type: ordinal
    sequence: [32, 64, 128, 256, 512, 1024, 2048]
  environment.n_envs:
    type: ordinal
    sequence: [4, 8, 16, 32]
  environment.n_total_timesteps:
    type: constant
    value: ${environment.n_total_timesteps}
  hp_config.update_epochs:
    type: uniform_int
    upper: 20
    lower: 1
    log: false
  nas_config.num_mlp_layers:
    type: uniform_int
    upper: 3
    lower: 1
    log: False
  nas_config.hidden_size:
    type: ordinal
    sequence: [32, 64, 128]
  profiling.env_step_time:
    type: constant
    value: ${profiling.env_step_time}
  profiling.inference_time:
    type: constant
    value: ${profiling.inference_time}
  profiling.grad_backprop_time:
    type: constant
    value: ${profiling.grad_backprop_time}