seed: 0
name: ppo_gpu_hybrid
hyperparameters:
  hp_config.learning_rate:
    type: uniform_float
    upper: 0.1
    lower: 1.0e-06
    log: true
  hp_config.gamma_loss_rate:
    type: uniform_float
    upper: 0.05
    lower: 0.001
    default_value: 0.01
    log: True
  hp_config.gae_lambda:
    type: uniform_float
    upper: 0.9999
    lower: 0.9
    log: false
  hp_config.ent_coef:
    type: uniform_float
    upper: 0.5 
    lower: 0.0
    log: false
  hp_config.vf_coef:
    type: uniform_float
    upper: 1.0
    lower: 0.0
    default_value: 0.5
    log: false
  environment.n_total_timesteps:
    type: constant
    value: ${environment.n_total_timesteps}
  hp_config.minibatch_size:
    type: ordinal
    sequence: [64, 128, 256, 512, 1024, 2048, 4096, 8192]
  hp_config.n_steps:
    type: ordinal
    sequence: [3, 5, 8, 16, 32, 64]
  environment.n_envs:
    type: ordinal
    sequence: [64, 128, 256, 512, 1024, 2048, 4096]
  hp_config.update_epochs:
    type: uniform_int
    upper: 10
    lower: 1
    log: False
  nas_config.num_mlp_layers:
    type: uniform_int
    upper: 3
    lower: 1
    log: False
  nas_config.hidden_size:
    type: ordinal
    sequence: [64, 128, 256, 512]