# @package _global_
defaults:
  - override /hydra/launcher: submitit_slurm

hydra:
  launcher:
    timeout_min: 90
    partition: c23ms
    cpus_per_task: 4
    account: p0021208
    setup:
      - module load GCCcore/12.2.0
      - module load Python/3.10.8
      - source /home/aq055502/projects/arlbench-smac-hyper/arlbench/.venv/bin/activate
      - export JAX_PLATFORM_NAME=cpu
